server:
  port: 8080

spring:
  security:
    user:
      name: admin
      password: 1q2w3e4r
    oauth2:
      client:
        registration:
          google:
            client-id: 33513345693-him0dn6uql2o81umdle4d8fhns5i4tjo.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          naver:
            client-id: zfGO8T7aFidmtY4Yqw73
            client-secret: weSU0uNtrS
            scope:
              - email
              - name
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response


  mvc:
    static-path-pattern: /static/**

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://web-study.ca7yqvnelwuw.ap-northeast-2.rds.amazonaws.com:3306/stussy-20220929-junil?allowMultiQueries=true
    username: admin
    password: 1q2w3e4r

mybatis:
  mapper-locations:
    - /mappers/*.xml

file:
  path: C:/mungi/web/springboot/stussy-clone-20220929-mungi/upload/
