server:
  port: 8080

spring:
  security:
    user:
      name: admin
      password: 1q2w3e4r

  mvc:
    static-path-pattern: /static/**

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://web-study.ca7yqvnelwuw.ap-northeast-2.rds.amazonaws.com:3306/stussy-20220929?allowMultiQueries=true
    username: admin
    password: 1q2w3e4r

mybatis:
  mapper-locations:
    - /mappers/*.xml

file:
  path: C:/mungi/web/springboot/stussy-clone-20220929-mungi/upload/
