server:
  port: 8080

spring:
  mvc:
    static-path-pattern: /static/**

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://web-study.ca7yqvnelwuw.ap-northeast-2.rds.amazonaws.com:3306/stussy-20220929
    username: admin
    password: 1q2w3e4r

mybatis:
  mapper-locations:
    -/mappers/*.xml
